### ISSUE TITLE
How to: Installation and analysis

### ISSUE THREAD

**Issue by Guillermo-Hidalgo-Gadea** [saptera/OptiFlex#1]
Hi all,
your OptiFlex preprint was remarkable, and I was trying to re-analyze some of my data to compare your approach to my current combination of DeepLabCut and Anipose.
Unfortunetly I'm experiencing some issues labeling data and running some scripts (e.g. label_conversion_json2heatmap.py), and I'm not sure if that may be due to faulty installation (e.g. errors finding OptiFlex modules to import, errors saving labels after Exit the GUI etc.).
Would you happen to have a set of instructions for newbies? 

All the Best, 
Guillermo

**Comment by si-yang** [comment]
**Hi Guillermo,**

Thanks for having interest in our OptiFlex.
With the info you give, it could be indeed related with an inappropriate installation.

To help you further, could you please providing us the following information?
1) The error message you get from the scripts that not able to run.
2) A screenshot when you running manual labeling which won't save.
3) If possible, provide us one of your JSON label flies.

Regards,
Si-yang

**Comment by Guillermo-Hidalgo-Gadea** [comment]
Hi Si-yang, 

thanks for the quick reply. 

When I run the Manual_Labelling_Tool.py GUI set on record mode and click Exit to finish, the GUI either closes without saving any label or JSON file in the output folder or freezes and returns following error message: 

`runfile('C:/Users/hidalggc/Documents/GitHub/OptiFlex/Manual_Labelling_Tool.py', wdir='C:/Users/hidalggc/Documents/GitHub/OptiFlex')
Traceback (most recent call last):

  File "C:\Users\hidalggc\Documents\GitHub\OptiFlex\OptiFlex\gui\manlbl_gui_func.py", line 140, in frame_signal
    manlbl_file_io(self.frameSlider.value())

  File "C:\Users\hidalggc\Documents\GitHub\OptiFlex\OptiFlex\gui\manlbl_gui_func.py", line 47, in manlbl_file_io
    lst_lbl.append(copy.deepcopy(lbl_dat[i]))

KeyError: 1`

Best Regards, 
Guillermo

**Comment by si-yang** [comment]
Hi Guillermo,

I'm sorry for the inconvenience that you have experienced.

For the problem that label GUI not saving labels is related to a glitch in the code. When you click the [prevButton] or [nextButton] in the "Manual Labelling Control" window instead of using keyboard shortcut [A] or [D], a GUI signaling is missing which will cause the labels not being saved. Now this problem is fixed, please update your local code.

For the problem that the GUI crashes when exit, with the error code, it seems that some key name in the label is the source of crash. This problem might be related with illegal names in your label list CSV file. Please try to avoid special characters like [+], [*], etc. and [SPACE].. Also make sure there are no label with the same name. If this error persists, you could send me a short piece of you video together with you label list CSV, I will investigate further.


Best regards,
Si-yang

**Comment by Guillermo-Hidalgo-Gadea** [comment]
Hi Si-yang, 

Thank you for the fast implementation, the prints are very useful!

Once I place a label though (not all due to occluded body parts), I get this error message in both cases, after pressing [next] and [d]: 

'runfile('C:/Users/hidalggc/Documents/GitHub/OptiFlex/Manual_Labelling_Tool.py', wdir='C:/Users/hidalggc/Documents/GitHub/OptiFlex')
Empty label data input, file not created!
Empty label data input, file not created!
Traceback (most recent call last):

  File "C:\Users\hidalggc\Documents\GitHub\OptiFlex\OptiFlex\gui\manlbl_gui_func.py", line 148, in frame_signal
    manlbl_file_io(self.frameSlider.value())

  File "C:\Users\hidalggc\Documents\GitHub\OptiFlex\OptiFlex\gui\manlbl_gui_func.py", line 47, in manlbl_file_io
    lst_lbl.append(copy.deepcopy(lbl_dat[i]))

KeyError: 0'

Here is a link to a shared data folder with my video files and label_list.csv. You can also find my email in the readme file.

https://ruhr-uni-bochum.sciebo.de/s/xPf7cyIWpriyB4l


Best Regards, 
Guillermo

**Comment by si-yang** [comment]
**Hi Guillermo,**

Sorry for the multiple issues with our GUI. And thanks a lot for your useful inputs!

I have found the cause of your issue, which related with a wrong way of handeling label dictionary. Now, instead of using index, the dictionary is directly called with key, which should address the error you experienced.

Please update you local code once more, and sorry again for the inconvenience.

Best regards,
Si-yang
